apiVersion: v1
data:
  new-hire-service.xml: |-
    <kie-server-state>
      <controllers>
        <string>http://pam-rhpamcentr:8080/rest/controller</string>
      </controllers>
      <configuration>
        <configItems>
          <config-item>
            <name>org.kie.server.controller.user</name>
            <value>controllerUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.controller.pwd</name>
            <value>controllerUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.user</name>
            <value>executionUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.pwd</name>
            <value>executionUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.controller</name>
            <value>http://pam-rhpamcentr:8080/rest/controller</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.id</name>
            <value>new-hire-service</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.location</name>
            <value>http://new-hire-service:8090/rest/server</value>
            <type>java.lang.String</type>
          </config-item>
        </configItems>
      </configuration>
      <containers>
          <container>
            <containerId>com.redhat:new-hire:1.0.0</containerId>
            <releaseId>
              <groupId>com.redhat</groupId>
              <artifactId>new-hire</artifactId>
              <version>1.0.0</version>
            </releaseId>
            <status>STARTED</status>
            <scanner>
              <status>STOPPED</status>
            </scanner>
            <configItems>
              <config-item>
                <name>KBase</name>
                <value></value>
                <type>BPM</type>
              </config-item>
              <config-item>
                <name>KSession</name>
                <value></value>
                <type>BPM</type>
              </config-item>
              <config-item>
                <name>MergeMode</name>
                <value>MERGE_COLLECTIONS</value>
                <type>BPM</type>
              </config-item>
              <config-item>
                <name>RuntimeStrategy</name>
                <value>PER_PROCESS_INSTANCE</value>
                <type>BPM</type>
              </config-item>
            </configItems>
            <messages/>
            <containerAlias></containerAlias>
          </container>
        </containers>
    </kie-server-state>
kind: ConfigMap
metadata:
  name: new-hire-service-kie-server-state