apiVersion: v1
data:
  settings.xml: |-
    <?xml version="1.0"?>
    <settings>
        <localRepository>/deployments/maven/repository</localRepository>
        <mirrors/>
        <servers/>

        <profiles>
            <!-- Configure the JBoss GA Maven repository -->
            <profile>
                <id>maven-all-public</id>
                <repositories/>
                </repositories>
                <pluginRepositories/>
            </profile>
        </profiles>
        <activeProfiles>
            <!-- Optionally, make the repository active by default -->
            <activeProfile>maven-all-public</activeProfile>
        </activeProfiles>

    </settings>
kind: ConfigMap
metadata:
  name: mvn-settings
