{
 "title": "Kie Server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Kie Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Instances",
   "type": "singlestat",
   "description": "Number of Process Instances",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_count\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Instances Aborted",
   "type": "singlestat",
   "description": "Number of aborted process instances",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances_aborted{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_aborted_count\"}"
    }
   ]
  },
  {
   "title": "Process Instances Active",
   "type": "singlestat",
   "description": "Number of active process instances",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances_active{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_active_count\"}"
    }
   ]
  },
  {
   "title": "Process Instances Completed",
   "type": "singlestat",
   "description": "Number of completed process instances",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances_completed{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_completed_count\"}"
    }
   ]
  },
  {
   "title": "Process Instances Pending",
   "type": "singlestat",
   "description": "Number of pending process instances",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances_pending{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_pending_count\"}"
    }
   ]
  },
  {
   "title": "Process Instances Suspended",
   "type": "singlestat",
   "description": "Number of suspended process instances",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instances_suspended{instance=~\".*\",job=\"kie-server\",unit=\"process_instances_suspended_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks",
   "type": "singlestat",
   "description": "Number of Human Tasks",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks{job=~\"kie-server.*\",unit=\"tasks_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks Ready",
   "type": "singlestat",
   "description": "Number of Human Tasks Ready",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks_ready{job=~\"kie-server.*\",unit=\"tasks_ready_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks Reserved",
   "type": "singlestat",
   "description": "Number of Human Tasks Reserved",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks_reserved{job=~\"kie-server.*\",unit=\"tasks_reserved_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks Completed",
   "type": "singlestat",
   "description": "Number of Human Tasks Completed",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks_completed{job=~\"kie-server.*\",unit=\"tasks_completed_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks InProgress",
   "type": "singlestat",
   "description": "Number of Human Tasks InProgress",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks_inprogress{job=~\"kie-server.*\",unit=\"tasks_inprogress_count\"}"
    }
   ]
  },
  {
   "title": "Human Tasks Exited",
   "type": "singlestat",
   "description": "Number of Human Tasks Exited",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kie_server_tasks_exited{job=~\"kie-server.*\",unit=\"tasks_exited_count\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} heap_used"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} nonheap_used"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} {{gc}}"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} {{gc}}"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"kie-server.*\"}",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  }
 ]
}